FROM python:3.12-bookworm@sha256:581429e3df12d76e6af4be5ab7d0e7fc2013eb57dc23d2de691411c8efdbb970

RUN apt-get update \
    && apt-get install -y --no-install-recommends tk8.6 tcl8.6 ffmpeg xvfb xauth build-essential zlib1g-dev \
    && ln -s /usr/share/tcltk/tcl8.6 /usr/share/tcltk/tcl8 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

COPY requirements.txt .
RUN LDFLAGS="-Wl,-z,relro,-z,now" PYINSTALLER_COMPILE_BOOTLOADER=1 python -m pip install --no-cache-dir --no-binary=pyinstaller -r requirements.txt pyinstaller==6.16.0

COPY . .
ENTRYPOINT ["pyinstaller"]
